import { readAntseedEvidence } from '../../../../src/antseed.js';
import { readWalletLinkEvidence } from '../../../../src/linkage.js';
import { readAntseedIntegrityStatus } from '../../../../src/antseed-integrity.js';
import { buildPreliminaryAssessment } from '../../../../src/assessment.js';
import ledgerSnapshot from '../../../../data/antseed-ledger-snapshot.json';
import integritySnapshot from '../../../../data/antseed-integrity-snapshot.json';

// The local snapshot is regenerated by the AntSeed sync command.
const integrityCache = new Map<string, any>();

export async function POST(request: Request) {
  try {
    const { wallet, includeLinkage = false } = await request.json() as { wallet?: string; includeLinkage?: boolean };
    if (!wallet || !/^0x[0-9a-fA-F]{40}$/.test(wallet)) {
      return Response.json({ error: 'Enter a valid Base wallet address beginning with 0x.' }, { status: 400 });
    }
    let antseed: any;
    try {
      antseed = await readAntseedEvidence({ wallet }, {
        // Continue from the durable snapshot cursor so verification never
        // leaves a silent gap between saved history and current Base events.
        eventSource: 'rpc', resumeFromBlock: Number(ledgerSnapshot.coverage.toBlock ?? 0) + 1, lookbackBlocks: 5_000, batchSize: 1_000, allowPartialCoverage: true,
      });
    } catch (error) {
      antseed = {
        source: 'antseed',
        wallet: wallet.toLowerCase(),
        found: false,
        activity: null,
        payments: null,
        error: error instanceof Error ? error.message : 'AntSeed public service unavailable',
        limitations: ['AntSeed public service was unavailable; local indexed evidence may still be shown.'],
      };
    }
    await preferCompleteLocalLedger(antseed, wallet);
    const integrity = await readStableIntegrityStatus(wallet);
    const customers = antseed.payments?.customers ?? [];
    let linkage = null;
    if (includeLinkage && customers.length) {
      try {
        // Inspect the five largest payer wallets. This is deliberately bounded:
        // Blockscout is a public service, and a clue is not ownership proof.
        linkage = await readWalletLinkEvidence(wallet, customers, { maxCustomers: 5, maxPagesPerWallet: 2 });
      } catch (error) {
        linkage = {
          source: 'base-blockscout',
          customers: [],
          error: error instanceof Error ? error.message : 'Wallet-link evidence unavailable',
          limitations: ['Wallet-link lookup failed; no ownership inference was made.'],
        };
      }
    }
    const assessment = buildPreliminaryAssessment({ wallet, antseed, ghbounty: null, linkage });
    const genLayerPreview = buildLocalJudgmentPreview(wallet, antseed, linkage, integrity);
    const genLayerInput = buildContractInput(wallet, antseed, linkage, integrity, genLayerPreview);
    const evidenceJson = JSON.stringify(genLayerInput);
    const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(evidenceJson));
    const reportId = `air-${Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('')}`;
    return Response.json({ wallet, antseed, linkage, integrity, assessment, genLayerPreview, genLayerInput, evidenceJson, reportId, checkedAt: new Date().toISOString() });
  } catch (error) {
    return Response.json({ error: error instanceof Error ? error.message : 'Verification failed.' }, { status: 500 });
  }
}

function buildLocalJudgmentPreview(wallet: string, antseed: any, linkage: any, integrity: any) {
  const payments = antseed.payments;
  const lifecycle = payments?.lifecycle;
  if (!payments?.settlementCount) {
    return {
      simulationOnly: true,
      policyVersion: 'agent-income-v2',
      verdict: 'no_payment_record',
      internalEvidenceLevel: 'no_wash_signals_found',
      incomeCredibility: 0,
      selfPaymentRisk: 0,
      evidenceSufficiency: 95,
      deliveryAcceptance: null,
      reasons: [{ code: 'missing_settlements', facts: {} }],
      citedWallets: [wallet.toLowerCase()],
    };
  }

  const payerCount = Number(payments.customers?.length ?? 0);
  const settlementCount = Number(payments.settlementCount ?? 0);
  const largestShare = Number(payments.largestCustomerShare ?? 1);
  const checkedLinks = linkage?.customers ?? [];
  const linked = checkedLinks.filter((item: any) => item.indicators?.length);
  const officialWashProof = Boolean(integrity?.provenWashTrader);
  const acceptanceRate = lifecycle?.buyerAcceptanceRate == null
    ? null
    : Number(lifecycle.buyerAcceptanceRate);

  // A successful AntSeed settlement already contains the buyer's signed
  // authorization. That is strong evidence that this amount was accepted.
  let credibility = 82;
  if (payerCount >= 20 && settlementCount >= 100) credibility += 8;
  if (acceptanceRate != null && acceptanceRate >= 0.9) credibility += 5;
  if (largestShare >= 0.8) credibility -= 25;
  else if (largestShare >= 0.5) credibility -= 12;
  if (officialWashProof) {
    const totalSettled = Number(payments.settledUsdc ?? 0);
    const provenWash = Number(integrity.provenWashVolumeUsdc ?? 0);
    const unprovenShare = totalSettled > 0
      ? Math.max(0, Math.min(1, 1 - provenWash / totalSettled))
      : 0;
    // A finalized wash proof overrides the normal activity-based score. The
    // remaining percentage is only the portion not covered by that proof; it
    // is not an assertion that the remainder is genuine income.
    credibility = Math.min(credibility, Math.round(unprovenShare * 100));
  }
  credibility = Math.max(0, Math.min(98, credibility));

  let selfPaymentRisk = 15;
  if (largestShare >= 0.8) selfPaymentRisk += 30;
  else if (largestShare >= 0.5) selfPaymentRisk += 15;
  selfPaymentRisk += Math.min(40, linked.length * 15);
  if (officialWashProof) {
    selfPaymentRisk = Math.max(90, Math.round(Number(integrity.provenWashShare ?? 0) * 100));
  }
  selfPaymentRisk = Math.max(0, Math.min(100, selfPaymentRisk));

  // Credibility and self-payment risk describe the same claimed revenue from
  // opposite directions. A high self-payment risk therefore caps credibility
  // at the unchallenged share instead of allowing contradictory scores.
  credibility = Math.min(credibility, Math.max(0, 100 - selfPaymentRisk));

  // Evidence sufficiency measures which durable evidence classes exist for the
  // report. It must not rise or fall because a public RPC has a transient error.
  const evidenceSufficiency = lifecycle ? 95 : 82;
  const internalEvidenceLevel = officialWashProof
    ? 'confirmed_wash_evidence'
    : linked.length > 0 || largestShare >= 0.5
      ? 'strong_wash_signals'
      : 'no_wash_signals_found';

  const reasons = [
    {
      code: 'verified_settlement_history',
      facts: { settlementCount, settledUsdc: Number(payments.settledUsdc ?? 0), payerCount },
    },
    {
      code: 'payer_concentration',
      facts: { wallet: payments.customerBreakdown?.[0]?.buyer ?? null, share: largestShare },
    },
    officialWashProof
      ? {
          code: 'official_wash_proof',
          facts: { provenWashShare: Number(integrity.provenWashShare ?? 0), provenWashVolumeUsdc: Number(integrity.provenWashVolumeUsdc ?? 0) },
        }
      : {
          code: 'official_wash_status',
          facts: { provenWashTrader: false },
        },
    linked.length
      ? { code: 'wallet_linkage_clues', facts: { linkedWalletCount: linked.length } }
      : {
          code: 'delivery_acceptance',
          facts: lifecycle
            ? { acceptedCount: Number(lifecycle.completedAcceptedChannelCount ?? 0), unpaidCount: Number(lifecycle.unpaidEndedChannelCount ?? 0) }
            : { acceptedCount: Number(antseed.activity?.uniqueChannels ?? 0), unpaidCount: null },
        },
  ];

  return {
    simulationOnly: true,
    policyVersion: 'agent-income-v2',
    verdict: officialWashProof || selfPaymentRisk >= 70 ? 'high_risk' : linked.length || largestShare >= 0.5 ? 'mixed' : 'credible',
    internalEvidenceLevel,
    incomeCredibility: credibility,
    selfPaymentRisk,
    evidenceSufficiency,
    deliveryAcceptance: acceptanceRate == null ? null : Math.round(acceptanceRate * 100),
    reasons,
    citedWallets: [wallet.toLowerCase(), ...(payments.customerBreakdown ?? []).slice(0, 5).map((item: any) => item.buyer)],
    limitations: [
      'This is a deterministic local rehearsal, not a GenLayer validator consensus result.',
      'No finalized wash proof is not the same as proof that every payer is independent.',
    ],
  };
}

async function readStableIntegrityStatus(wallet: string) {
  const key = wallet.toLowerCase();
  let lastError: unknown;
  for (let attempt = 0; attempt < 2; attempt += 1) {
    try {
      const result = await readAntseedIntegrityStatus(wallet);
      integrityCache.set(key, result);
      return result;
    } catch (error) {
      lastError = error;
      if (attempt === 0) await new Promise((resolve) => setTimeout(resolve, 150));
    }
  }
  const cached = integrityCache.get(key);
  if (cached) {
    return { ...cached, sourceStatus: 'using_last_successful_read' };
  }
  const saved = (integritySnapshot.sellers as Record<string, any>)[key];
  if (saved) {
    return { ...saved, sourceStatus: 'using_local_snapshot', snapshotThroughBlock: integritySnapshot.toBlock };
  }
  return {
    source: 'antseed-onchain-wash-registry',
    registryAddress: integritySnapshot.registryAddress,
    seller: key,
    status: 'no_finalized_wash_proof',
    provenWashTrader: false,
    provenWashVolumeRaw: '0',
    provenWashVolumeUsdc: 0,
    totalSellerVolumeRaw: '0',
    totalSellerVolumeUsdc: 0,
    provenWashShareBps: 0,
    provenWashShare: 0,
    evidenceDigest: null,
    sourceStatus: 'using_local_snapshot',
    snapshotThroughBlock: integritySnapshot.toBlock,
    error: lastError instanceof Error ? lastError.message : 'AntSeed integrity registry unavailable',
  };
}

async function preferCompleteLocalLedger(antseed: any, wallet: string) {
  try {
    const ledger = (ledgerSnapshot.sellers as Record<string, any>)[wallet.toLowerCase()];
    if (!ledger) return;
    const requiredBlock = Number(antseed.activity?.lastSettledBlock ?? ledger.lastSettledBlock ?? 0);
    const indexedThrough = Number(ledgerSnapshot.coverage.toBlock ?? 0);
    const recent = antseed.payments;
    const recentFrom = Number(recent?.coverage?.fromBlock ?? 0);
    const recentComplete = Boolean(recent?.coverage?.completeWindow);
    const contiguousRecentWindow = recentFrom > 0 && indexedThrough + 1 >= recentFrom;
    // The saved ledger starts before AntSeed's earliest known channel activity.
    // Its cursor advances only after a range is read successfully. A contiguous
    // recent RPC window then bridges the saved cursor to the latest known event.
    const startsBeforeKnownActivity = Number(ledgerSnapshot.coverage.fromBlock ?? Infinity) <= 44_472_648;
    const coversLatestKnownSettlement = indexedThrough >= requiredBlock ||
      (contiguousRecentWindow && recentComplete && Number(recent.coverage.toBlock) >= requiredBlock);
    const completeHistory = startsBeforeKnownActivity && requiredBlock > 0 && coversLatestKnownSettlement;
    antseed.localLedger = {
      ...ledger,
      ledgerCoverage: ledgerSnapshot.coverage,
      completeHistory,
      indexedThrough,
      requiredBlock,
    };
    if (ledger.settlementCount > 0) antseed.found = true;
    antseed.payments = mergeLedgerWithRecent(ledger, recent, indexedThrough, completeHistory);
  } catch (error) {
    antseed.localLedgerError = error instanceof Error ? error.message : 'Local ledger unavailable';
  }
}

function mergeLedgerWithRecent(ledger: any, recent: any, indexedThrough: number, completeHistory: boolean) {
  const byCustomer = new Map<string, bigint>();
  for (const customer of ledger.customers ?? []) {
    byCustomer.set(customer.buyer, BigInt(customer.settledRaw ?? '0'));
  }
  let total = BigInt(ledger.settledRaw ?? '0');
  let additionalSettlements = 0;
  for (const event of recent?.events ?? []) {
    if (event.type !== 'settled' || Number(event.blockNumber) <= indexedThrough) continue;
    const amount = BigInt(event.deltaRaw ?? '0');
    total += amount;
    additionalSettlements += 1;
    byCustomer.set(event.buyer, (byCustomer.get(event.buyer) ?? 0n) + amount);
  }
  const customerBreakdown = [...byCustomer.entries()].map(([buyer, amount]) => ({
    buyer,
    settledRaw: amount.toString(),
    settledUsdc: Number(amount) / 1_000_000,
    share: total === 0n ? 0 : Number((amount * 1_000_000n) / total) / 1_000_000,
  })).sort((a, b) => b.settledUsdc - a.settledUsdc);
  return {
      chain: 'base-mainnet',
      source: 'agentproof-ledger-plus-recent-rpc',
      contract: recent?.contract,
      coverage: {
        fromBlock: Number(ledgerSnapshot.coverage.fromBlock ?? 44_000_000),
        toBlock: Math.max(indexedThrough, Number(recent?.coverage?.toBlock ?? 0)),
        completeHistory,
        // The stored range itself is contiguous even when newer chain activity
        // exists beyond the snapshot and lifetime coverage is therefore stale.
        completeWindow: true,
        failedRanges: recent?.coverage?.failedRanges ?? [],
      },
      customers: customerBreakdown.map((customer) => customer.buyer),
      customerBreakdown,
      settledRaw: total.toString(),
      settledUsdc: Number(total) / 1_000_000,
      settlementCount: Number(ledger.settlementCount ?? 0) + additionalSettlements,
      lifecycle: ledger.lifecycle ?? null,
      largestCustomerShare: customerBreakdown[0]?.share ?? null,
      firstSettledBlock: ledger.firstSettledBlock,
      lastSettledBlock: Math.max(Number(ledger.lastSettledBlock ?? 0), Number(recent?.events?.at(-1)?.blockNumber ?? 0)),
      unusedReserveReturnedUsdc: ledger.lifecycle?.unusedReserveReturnedUsdc ?? null,
      disputeRefundUsdc: null,
      events: recent?.events?.filter((event: any) => Number(event.blockNumber) > indexedThrough) ?? [],
    };
}

function buildContractInput(wallet: string, antseed: any, linkage: any, integrity: any, assessment: any) {
  const payments = antseed.payments;
  const activity = antseed.activity;
  return {
    schemaVersion: '0.4.0',
    subjectWallet: wallet.toLowerCase(),
    computedAssessment: {
      policyVersion: assessment.policyVersion,
      internalEvidenceLevel: assessment.internalEvidenceLevel,
      incomeCredibility: assessment.incomeCredibility,
      selfPaymentRisk: assessment.selfPaymentRisk,
      evidenceSufficiency: assessment.evidenceSufficiency,
      deliveryAcceptance: assessment.deliveryAcceptance,
    },
    sources: {
      antseed: {
        found: Boolean(antseed.found),
        agentId: antseed.agentId,
        requests: activity ? Number(activity.totalRequests ?? 0) : null,
        settlements: payments?.settlementCount ?? (activity ? Number(activity.settlementCount ?? 0) : null),
        reportedUniqueBuyers: payments?.customers?.length ?? (activity ? Number(activity.uniqueBuyers ?? 0) : null),
        paymentCoverage: payments?.coverage ?? null,
        settledUsdc: payments?.settledUsdc ?? null,
        settlementCount: payments?.settlementCount ?? null,
        payerWalletCount: payments?.customers?.length ?? null,
        delivery: {
          buyerApprovedRequests: activity ? Number(activity.totalRequests ?? 0) : null,
          buyerApprovedInputTokens: activity ? Number(activity.totalInputTokens ?? 0) : null,
          buyerApprovedOutputTokens: activity ? Number(activity.totalOutputTokens ?? 0) : null,
          channelLifecycle: payments?.lifecycle ?? null,
        },
        unusedReserveReturnedUsdcInWindow: payments?.unusedReserveReturnedUsdc ?? null,
        largestCustomerShare: payments?.largestCustomerShare ?? null,
        topCustomers: (payments?.customerBreakdown ?? []).slice(0, 5),
      },
      walletLinkage: (linkage?.customers ?? []).map((item: any) => ({
        customerWallet: item.customerWallet,
        indicators: item.indicators,
        directTransfers: item.directTransfers,
        commonNativeFunders: item.commonNativeFunders,
        commonUsdcFunders: item.commonUsdcFunders,
        recentHistoryTruncated: item.recentHistoryTruncated,
        lookupErrors: item.lookupErrors,
      })),
      antseedIntegrity: integrity,
    },
    interpretationRules: {
      ordinaryTransferIsNotIncome: true,
      linkageIndicatorIsNotOwnershipProof: true,
      partialWindowIsNotLifetimeRevenue: true,
      successfulSettlementContainsBuyerSignedApproval: true,
      endedWithoutPaymentMeansDeliveryWasNotBuyerApproved: true,
      endedWithoutPaymentDoesNotByItselfAssignFault: true,
      unusedReserveReturnIsNotDisputeRefund: true,
    },
    missingEvidence: [
      'verified cross-platform identity binding',
      ...(payments?.coverage?.completeHistory ? [] : ['complete payment history']),
      'conclusive wallet ownership proof',
    ],
  };
}
